# Generated by Django 4.1.3 on 2022-11-09 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('spice', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_bistro.category')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_bistro.diet')),
            ],
        ),
        migrations.DeleteModel(
            name='menu_items',
        ),
    ]
